ACAD-857 overwrote the prod sis xfer script with the new parameterized template from test and configured both prod and test to use it

diff --git a/modules/oipp/templates/oipp_csv_copy.sh.erb b/modules/oipp/templates/oipp_csv_copy.sh.erb
--- a/modules/oipp/templates/oipp_csv_copy.sh.erb
+++ b/modules/oipp/templates/oipp_csv_copy.sh.erb
@@ -1,41 +1,183 @@
 MAILTO=""
 
-CSV_DIR=<%= scope.lookupvar('sis::batch::csv_dir') %>
+DEBUG_OUT=false;
 
-# set correct permissions
-chown -fR "rsmart:rsmart" /home/ucb_sis/*csv
-chown -fR "rsmart:rsmart" /home/ucd_sis/*csv
-chown -fR "rsmart:rsmart" /home/ucm_sis/*csv
-chown -fR "rsmart:rsmart" /home/ucb_sis/test/*
-chown -fR "rsmart:rsmart" /home/ucd_sis/test/*
-chown -fR "rsmart:rsmart" /home/ucm_sis/test/*
+CLE_PROC_DIR=<%= scope.lookupvar('oipp::sis::cle_csv') %>
+OAE_PROC_DIR=<%= scope.lookupvar('oipp::sis::oae_csv') %>
+LOG=<%= scope.lookupvar('oipp::sis::sis_log') %>
+ARCHIVE_ROOT=<%= scope.lookupvar('oipp::sis::sis_error_archive') %>
+FILE_OWNER=<%= scope.lookupvar('oipp::sis::file_owner') %>
+ARCHIVE_DIR=$ARCHIVE_DIR/`date +%Y%m%d-%H%M`;
+REMOTE=<%= scope.lookupvar('oipp::sis::use_scp') %>
+PRODUCTION=<%= scope.lookupvar('oipp::sis::production') %>;
 
-# temporary: copy UCD & UCM prod files to test also (will get overwritten if anything is uploaded to test)
-scp -p /home/ucd_sis/*.UCD.csv	        rsmart@oipp-cle1:/files-cle/files/sis/test
-scp -p /home/ucm_sis/*.UCMerced.csv	    rsmart@oipp-cle1:/files-cle/files/sis/test
-scp -p /home/ucb_sis/*.UCB.csv	        rsmart@oipp-cle1:/files-cle/files/sis/test
+log()
+{
+    LOG_LEVEL=$1;
+    LOG_MESSAGE=$2;
+    DATE_STR=`date +"%m/%d/%Y %H:%M:%S"`;
 
-scp -p /home/ucd_sis/*csv		        ucd_sis@oipp-test:/home/ucd_sis
-scp -p /home/ucm_sis/*csv		        ucm_sis@oipp-test:/home/ucm_sis
-scp -p /home/ucb_sis/*csv		        ucb_sis@oipp-test:/home/ucb_sis
-# end temporary
+    echo "$DATE_STR [$LOG_LEVEL]: $LOG_MESSAGE" >> $LOG;
+}
 
-# copy test user file to prod server for OAE user creation
-scp -p /home/ucb_sis/test/*.UCB.csv      rsmart@oipp-cle1:/files-cle/files/sis/test
-scp -p /home/ucd_sis/test/*.UCD.csv      rsmart@oipp-cle1:/files-cle/files/sis/test
-scp -p /home/ucm_sis/test/*.UCMerced.csv rsmart@oipp-cle1:/files-cle/files/sis/test
+debug()
+{
+    if $DEBUG_OUT ; then
+        log "DEBUG" "$1";
+    fi;
+}
 
-# copy all test csv files to test server
-scp -p /home/ucb_sis/test/* ucb_sis@oipp-test:/home/ucb_sis/test && rm -f /home/ucb_sis/test/*
-scp -p /home/ucd_sis/test/* ucd_sis@oipp-test:/home/ucd_sis/test && rm -f /home/ucd_sis/test/*
-scp -p /home/ucm_sis/test/* ucm_sis@oipp-test:/home/ucm_sis/test && rm -f /home/ucm_sis/test/*
+error()
+{
+    log "ERROR" "$1";
+}
 
-# copy all prod csv files to prod CLE server
-scp -p /home/ucb_sis/*csv rsmart@oipp-cle1:/files-cle/files/sis
-scp -p /home/ucd_sis/*csv rsmart@oipp-cle1:/files-cle/files/sis
-scp -p /home/ucm_sis/*csv rsmart@oipp-cle1:/files-cle/files/sis
+info()
+{
+    log "INFO" "$1";
+}
 
-# copy all prod csv files to prod OAE server and remove files
-scp -p /home/ucb_sis/*csv rsmart@oipp-prod-app1:$CSV_DIR && rm -f /home/ucb_sis/*csv
-scp -p /home/ucd_sis/*csv rsmart@oipp-prod-app1:$CSV_DIR && rm -f /home/ucd_sis/*csv
-scp -p /home/ucm_sis/*csv rsmart@oipp-prod-app1:$CSV_DIR && rm -f /home/ucm_sis/*csv
+archive()
+{
+    SOURCES="$1";
+
+    if [ ! -e "$ARCHIVE_DIR" ] ; then
+        mkdir -p "$ARCHIVE_DIR";
+    fi
+
+    if [ ! -w "$ARCHIVE_DIR" ] ; then
+        error "Cannot write to archive directory: $ARCHIVE_DIR";
+        return 1;
+    fi
+
+    if [ ! -d "$ARCHIVE_DIR" ] ; then
+        error "Cannot archive. $ARCHIVE_DIR is not a directory";
+    fi
+
+    mv "$SOURCES" "$ARCHIVE_DIR";
+}
+
+transferSISFiles()
+{
+    SOURCE_FILES=$1;
+    DEST_DIR=$2;
+
+    if [ -z $3 ] ; then
+        CP=cp;
+    else
+        CP=$3;
+    fi;
+
+    debug "transferring $SOURCE_FILES to $DEST_DIR";
+
+    # set correct permissions
+    chown -fR "$FILE_OWNER" "$SOURCE_FILES";
+
+    if [ $? -ne 0 ] ; then
+    {
+        error "Could not set permissions for $SOURCE_FILES"
+        return $?
+    }
+
+    # copy files
+    $CP "$SOURCE_FILES" "$DEST_DIR";
+}
+
+doAllTransfers ()
+{
+    SOURCE_DIR=$1;
+    ABBREV=$2;
+    CP=$3;
+    PROD_FILES=$SOURCE_DIR/*.$ABBREV.csv;
+    TEST_FILES=$SOURCE_DIR/test/*;
+    ERRORS=false;
+
+    debug "SOURCE_DIR=$SOURCE_DIR";
+    debug "ABBREV=$ABBREV";
+
+    if [ -e $PROD_FILES ] ; then
+
+        if $PRODUCTION; then
+            oipptest="oipp-test:$SOURCE_DIR";
+            info "copying $ABBREV files to OIPP test";
+            transferSISFiles "$PROD_FILES" "$oipptest" scp;
+            if [ $? -ne 0 ] ; then
+                ERRORS=true;
+                error "Failed to copy $PROD_FILES to $CLE_PROD_DIR/test";
+            fi;
+        fi;
+
+        info "copying $ABBREV files to CLE test";
+        transferSISFiles "$PROD_FILES" "$CLE_PROD_DIR/test" $CP;
+        if [ $? -ne 0 ] ; then
+            ERRORS=true;
+            error "Failed to copy $PROD_FILES to $CLE_PROD_DIR/test";
+        fi;
+
+        info "copying $ABBREV files to CLE";
+        transferSISFiles "$PROD_FILES" "$CLE_PROD_DIR" $CP;
+        if [ $? -ne 0 ] ; then
+            ERRORS=true;
+            error "Failed to copy $PROD_FILES to $CLE_PROD_DIR";
+        fi;
+
+        info "copying $ABBREV files to OAE";
+        transferSISFiles "$PROD_FILES" "$OAE_PROD_DIR" $CP;
+        if [ $? -ne 0 ] ; then
+            ERRORS=true;
+            error "Failed to copy $PROD_FILES to $OAE_PROD_DIR/test";
+        fi;
+
+        if [ $ERRORS ] ; then
+            info "production files successfully copied"
+            rm -f $PROD_FILES;
+        else
+            archive $PROD_FILES;
+            error "Errors occured during file transfer; Import files have been copied to $ARCHIVE_DIR";
+        fi;
+    fi;
+
+    if [ -e $TEST_FILES ] ; then
+        ERRORS=false;
+
+        info "Copying test files to CLE test";
+        transferSISFiles "$TEST_FILES" "$CLE_PROC_DIR/test" $CP;
+        if [ $? -ne 0 ] ; then
+            ERRORS=true;
+            error "Failed to copy $TEST_FILES to $CLE_PROC_DIR/test";
+        fi;
+
+        if $PRODUCTION ; then
+            oipptest="oipp-test:$SOURCE_DIR/test/";
+            info "copying test files to OIPP test";
+            transferSISFiles "$TEST_FILES" "$oipptest" scp;
+            if [ $? -ne 0 ] ; then
+                ERRORS=true;
+                error "Failed to copy $TEST_FILES to $oipptest";
+            fi;
+        fi;
+
+        if $ERRORS ; then
+            archive "$TEST_FILES";
+            error "Errors occured transfering test files; Test import files have been copied to $ERROR_ARCHIVE";
+        else
+            info "test files successfully copied";
+            rm -f "$TEST_FILES";
+        fi;
+
+    fi;
+}
+
+info "Started SIS file transfer";
+
+if $REMOTE ; then
+    CP=scp;
+else
+    CP=cp;
+fi;
+
+<% csv_schools.each do |school| -%>
+doAllTransfers "<%= school[0] %>" "<%= school[1] %>" $CP;
+<% end -%>
+
+info "SIS file transfers complete";
